### ISSUE TITLE
An item with the same key has already been added

### ISSUE THREAD

**Issue by digitalgym** [ghorsey/OpenGraph-Net#11]
When parsing page tags I get an exception "An item with the same key has already been added". Is there a way to handle this gracefully or determine the key that is being inserted?

**Comment by ghorsey** [comment]
@digitalgym I'm still struggling to recreate this exception.  Let me know if you can send a HTML snippet or a URL as an example... I haven't been able to recreate it.

**Comment by ghorsey** [comment]
Closing the issue since I never got additional information.
