### ISSUE TITLE
Check scheme

### ISSUE THREAD

**Issue by cecilphillip** [ghorsey/OpenGraph-Net#12]
Would you be open to adding a scheme check at the beginning of your ParseUrl methods that accept strings? This is more of a convenience/usability enhancement so we don't have to keep checking for schemes in our code

```csharp
 if (!Regex.IsMatch(url, @"^https?:\/\/", RegexOptions.IgnoreCase))
                        url = "http://" + url;
```

**Comment by ghorsey** [comment]
Are you talking about allowing the user to call the ParseUrl like the following?

    OpenGraph.ParseUrl("www.amazon.com")
    OpenGraph.ParseUrl("https://www.amazon.com")
    OpenGraph.ParseUrl("http://www.amazon.com")

Where right now, it expects the latter two?

If that's what you're asking for, I think it's a reasonable request and I can get it added.

**Comment by cecilphillip** [comment]
Yes please. That would be great
