### ISSUE TITLE
The request was aborted: Could not create SSL/TLS secure channel. 

### ISSUE THREAD

**Issue by Hellsystem86** [ghorsey/OpenGraph-Net#14]
When importing a URL from Github (example) The title/other data of the page is not recognized well.

And will always result in "The request was aborted: Could not create SSL/TLS secure channel. "

**Comment by ghorsey** [comment]
Is there a specific url, or does this happen for any tls/ssl url? I've not come across this before.

If you have a url I can use to test that would be helpful; otherwise I'll just try a random GitHub url...

Thanks for the report, I'll try and get this resolved this weekend.

**Comment by Hellsystem86** [comment]
This happens for any tls/ssl url from the same server like (Github) in this case.  Every github URL will result in this "titel". 

When I use the same code base (project) and I importing a URL from let's say YouTube(https) it works liks perfect.

I will edit this issue later today, when I'm found a link with will result in the same error.  👍

**Comment by ghorsey** [comment]
Could you send me how you're making the call?  Right now I cannot recreate this using either URLs from Github or you're supplied www.jeremyblum.com link.

I have attempted this in a unit test and it seems like I'm getting the code back correctly...

![image](https://user-images.githubusercontent.com/448706/52169229-d8520480-26e9-11e9-955e-08c329b2c75d.png)

**Comment by ghorsey** [comment]
Since there hasn't been any follow-up on this; I am going to close this issue.  

If it's still a problem for you @Hellsystem86 let me know and I'll see what I can do to help.

**Comment by kcoderhere** [comment]
I'm getting this exact error with using OpenGraph.ParseUrl("https://fortune.com/2019/05/26/summer-travel-tech-guide/")

Other URLs appear to be working just fine though.

**Comment by kcoderhere** [comment]
A few more examples of broken URLs:
https://www.cntraveler.com/story/how-cruise-lines-are-getting-more-eco-friendly
https://www.nytimes.com/2019/05/22/travel/leaping-caimans-and-tasty-piranha-in-the-wild-amazon.html
https://www.thrillist.com/travel/nation/visiting-hainan-things-to-know

But these work:
https://www.travelandleisure.com/food-drink/wine/english-wine-industry-booming
https://www.cnn.com/travel/article/abandoned-sacred-places-world/index.html

**Comment by ghorsey** [comment]
I'll look into this this weekend.

Are you using a dotnet core v3 project or a v2?  (I have this library supporting both netstandard2.0 and netstandard2.1).

**Comment by kcoderhere** [comment]
Not using dotnet core, MVC 5 project instead.

**Comment by ghorsey** [comment]
@kcoderhere 

> Just to make it more confusing, it breaks when I run this code locally on my Windows 10 machine, but it works when I run it on Windows 2016 Server.

Which version of the dotnet framework are you running locally vs on the windows server?

`netstandard2.0` needs version 4.6.1 as a minimum.  (netstandard2.1 no longer supports the windwos framework)

**Comment by ghorsey** [comment]
@kcoderhere, found the bug for framework 4.7.1

**Comment by ghorsey** [comment]
@kcoderhere  if you want to test when version `3.2.4` is live on nuget and let me know.

Fix seems to be adding target framework `net472` in addition to the `netstandard2.0`.  

Maybe the server works because it has dotnet core 2.0+ installed while you are missing it locally?
