### ISSUE TITLE
Nullreference exception thrown in GetPageAsync

### ISSUE THREAD

**Issue by cecilphillip** [ghorsey/OpenGraph-Net#15]
**Describe the bug**
The call to GetPageAsync in HttpDownLoader throws an exception when I try to retrieve `https://marketplace.visualstudio.com/items?itemName=sdras.vue-vscode-extensionpack`. It throws a NullReference exception on line [146](https://github.com/ghorsey/OpenGraph-Net/blob/develop/src/OpenGraphNet/HttpDownloader.cs#L146) when executing `if (response.ContentEncoding.ToLower().Contains("gzip"))`.

**To Reproduce**
HttpDownloader downloader = new HttpDownloader("https://marketplace.visualstudio.com/items?itemName=sdras.vue-vscode-extensionpack", "test", "test");
string html = await downloader.GetPageAsync();

**Expected behavior**
Not to throw.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 3.1.0

**Comment by ghorsey** [comment]
I just pushed v3.1.1 to nuget with this fixed.
