### ISSUE TITLE
Follow HTTP redirects

### ISSUE THREAD

**Issue by cecilphillip** [ghorsey/OpenGraph-Net#17]
**Is your feature request related to a problem? Please describe.**
When requests return an HTTP redirects like 301 status codes,  `ParseUrlAsync` throws an exception 

**Describe the solution you'd like**
set `AllowAutoRedirect` to true on  `HttpWebRequest`

**Comment by ghorsey** [comment]
I changed some internal base classes, and added the allow auto redirect for you.

Things are being indexed by nuget now.
