### ISSUE TITLE
make Microsoft.CodeAnalysis.FxCopAnalyzers a private dependency

### ISSUE THREAD

**Issue by elomonaco** [ghorsey/OpenGraph-Net#18]
Hi,

love the library, thank you. This is a minor request, it'd be nice if the package ```Microsoft.CodeAnalysis.FxCopAnalyzers``` would be set to private like ```StyleCop.Analyzers``` is.

otherwise this is a great library 👍

**Comment by ghorsey-opt** [comment]
Great suggestion.  I didn't even consider this.  I'll push an update this evening.

**Comment by ghorsey** [comment]
Great suggestion, which I didn't even consider.  I'll push an update to nuget this evening.

**Comment by ghorsey** [comment]
Done.
