### ISSUE TITLE
graph Description property missing?

### ISSUE THREAD

**Issue by jholovacs** [ghorsey/OpenGraph-Net#22]
**Describe the bug**
```csharp
var graph = await OpenGraph.ParseUrlAsync(myUrl);
var description = graph.Description;
```
the `graph` object does not have a property for `Description`...

OpenGraph-Net v3.2.4 from Nuget

**Comment by ghorsey** [comment]
Hey @jholovacs,

Sorry for the late reply.

There are only a few convenience methods on the `OpenGraph` object, but you can get at the other properties from the `OpenGraph.Metdata` object.

See the instructions here: http://ghorsey.github.io/OpenGraph-Net/documentation/accessing-values.html
