### ISSUE TITLE
YouTube video returns no meta

### ISSUE THREAD

**Issue by AndaHendriksen** [ghorsey/OpenGraph-Net#24]
When I try to get the meta data from a youtube video it is empty. It has worked before, but suddenly stopped working. Other url's works as promised.
![image](https://user-images.githubusercontent.com/10062572/100473880-afc9a480-30df-11eb-8d1a-bcb09f431e2e.png)

If I render the html from "OriginalHtml" it returns this:
![image](https://user-images.githubusercontent.com/10062572/100473945-d7207180-30df-11eb-84b7-0bc0fab48ede.png)

As said YouTube used to work, but now it doesn't - both on localhost or on the live server. Have both my IP's been blocked? Have you ever experienced that and do you have any suggestions on how to fix it?

Thanks!

**Comment by starforce** [comment]
Having same problem. YouTube metadata isn't returned

**Comment by starforce** [comment]
This is a great solution.. You will need to fine tune it..

https://codeshare.co.uk/blog/how-to-scrape-meta-data-from-a-url-using-htmlagilitypack-in-c/

**Comment by jack-shuster** [comment]
bump

**Comment by ulfmollerstrom** [comment]
Same problem on spotify... 
Preview works on dev.facebook.

https://open.spotify.com/track/0y7t0yzjtoz2e8wbevwsqo?si=7fjbllwzraujrp6f69hyrw

**Comment by ulfmollerstrom** [comment]
> This is a great solution.. You will need to fine tune it..
> 
> https://codeshare.co.uk/blog/how-to-scrape-meta-data-from-a-url-using-htmlagilitypack-in-c/

Not working either... Used a variation on that, but it's not getting OpenGraph-tags from YT or Spotify.

**Comment by ghorsey** [comment]
Sorry everyone been super slammed on the day job. I'll do my best to cycle on this this weekend

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by noycey** [comment]
I've just come across the same issue. Looks like it's because the og: tags are outside the <head> block so getting cut out by the MakeDocumentToParse function.

**Comment by ploring04** [comment]
Getting the same issue

**Comment by ghorsey** [comment]
Hey all, I'm looking into this item today.

Can anybody send any sample URLs  that are causing you problems.

I am investigating youtube and spotify today.

**Comment by ploring04** [comment]
@ghorsey i just tried it with this one and did not get any data back from the library

https://www.youtube.com/watch?v=QhTIifE5UCA&ab_channel=DeX

https://www.opengraph.xyz/url/https:%2F%2Fwww.youtube.com%2Fwatch%3Fv=QhTIifE5UCA&ab_channel=DeX/

**Comment by ghorsey** [comment]
@ploring04 I see the issue w/ the YT URLs, they've moved the `<meta property` tags into the body.  I am working on a unit test to fix that issue.

For the opengraph.xyz site the issue is that url is returning a 404, so that's a site problem there:
![image](https://user-images.githubusercontent.com/448706/106053482-b8b70200-609f-11eb-902b-8a43a60651f9.png)

**Comment by ghorsey** [comment]
The fix for handling meta tags in the body are coming in release v3.2.6 (I had to update some package info that I missed).

cc: @starforce @AndaHendriksen @ulfmollerstrom  @ploring04 @jack-shuster @noycey
