### ISSUE TITLE
unable to get graph even with user agent specified

### ISSUE THREAD

**Issue by Michael-Anderlin** [ghorsey/OpenGraph-Net#31]
Hello,

We are using you package (V3.2.6) to successfully get open graph from user entered URL.
With the following URL, it doesn't work. 

_https://www.nasdaq.com/boardvantage/board-portal?utm_medium=ppc@utm_source=google&utm_term=boardroom%20software&gclid=Cj0KCQjwh_eFBhDZARIsALHjlKf3nzPwT2d6QCIYjHbN5UVrpwJvD0gixyDMuUI66RdSpWjfCzEqoT8aAkXfEALw_wcB_

With Curl, I make it work by adding a user agent from Chrome.

curl --user-agent 'Mozilla/5.0 (Linux; Android 10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.88 Mobile Safari/537.36' 'https://www.nasdaq.com/boardvantage/board-portal?utm_medium=ppc@utm_source=google&utm_term=boardroom%20software&gclid=Cj0KCQjwh_eFBhDZARIsALHjlKf3nzPwT2d6QCIYjHbN5UVrpwJvD0gixyDMuUI66RdSpWjfCzEqoT8aAkXfEALw_wcB' | head -20

Even if I add a user agent in the call to 
graph = await OpenGraph.ParseUrlAsync(url,userAgent);
it still doesn't work

The user agent is the one from the calling browser or 
"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
by default.

Can you help me?

Regards,

Michael

**Comment by Michael-Anderlin** [comment]
Hello,

Do you have some idea about it ?

Tx,

Michael

**Comment by Michael-Anderlin** [comment]
Hello,
We need it badly, could you help us please ?

KR,

Michael

**Comment by Michael-Anderlin** [comment]
Hello @ghorsey,
I still need a solution for that.
Could you check it please ?
Tx a lot

**Comment by ghorsey** [comment]
Hey @Michael-Anderlin,

Sorry I've been MIA.  I'll look into this, this evening after the day job.

Just to validate, I went to the URL mentioned above in Chrome and saw these OG tags:
![image](https://user-images.githubusercontent.com/448706/127042497-f3786c6f-a0d8-4f84-bbd1-5e43e193721a.png)

And it's these tags that you are saying are not loading when you try using the OpenGraph.Net library.

**Comment by Michael-Anderlin** [comment]
Hello @ghorsey,

Yes, that's it. It's because there are no user agent sent to the remote site.
Look at my first message, I've done test with CURL.

Thank you for your help.

KR

**Comment by ghorsey** [comment]
@Michael-Anderlin This URL/site has an issue witht the default `facebookexternalhit` user agent.

You can work around this by specifying a different default user-agent in the [ParseUrl](https://ghorsey.github.io/OpenGraph-Net/api/OpenGraphNet.OpenGraph.html#OpenGraphNet_OpenGraph_ParseUrlAsync_System_Uri_System_String_System_Boolean_System_Int32_) method.

**Comment by ghorsey** [comment]
I just tested setting the default `user-agent` to an empty string and your endpoint also continues to work.  I'll roll out an update for 3.2.8 where I remove the `facebookexternalhit` default `user-agent`.

**Comment by ghorsey** [comment]
v3.2.8 has been published and should be available soon on nuget.org
