### ISSUE TITLE
encoding issues

### ISSUE THREAD

**Issue by coronag** [ghorsey/OpenGraph-Net#4]
using nuget 1.2.0.1 

-- For instance : 
var ogTags = OpenGraph.ParseUrl("https://vk.com/wall-41600377_66756");
Console.WriteLine(ogTags["description"]);

=> encoding is not correct.

It seams github source code is correct, is it that nuget.org is not up to date ? Can you please push a newer version on nuget ? 

Thanks.

**Comment by coronag** [comment]
@ghorsey - do you plan to push a new release on nuget.org ? It will be very appreciated :).

**Comment by ghorsey** [comment]
Sorry @coronag let me check this today I'll try and get something pushed up.

**Comment by coronag** [comment]
Ok thanks for the update.

**Comment by ghorsey** [comment]
@coronag I've got this issue published as version 1.3.0.1 on nuget.

Sorry it's been taking me so long to get through these items.. been stuck travelling for work...
