### ISSUE TITLE
Some websites do have og:image "html encoded" 

### ISSUE THREAD

**Issue by coronag** [ghorsey/OpenGraph-Net#5]
I ran into an issue with some website having og:image "html encoded".

For instance 
https://www.periscope.tv/w/1DXxyZZZVykKM
=> image when parsing is not visible...

=> just did this trick to avoid that issue  (OpenGraph.cs) :
var theVal = (property ?? "").Equals("image", StringComparison.InvariantCultureIgnoreCase)
                   ? System.Web.HttpUtility.HtmlDecode((value ?? ""))
                    : value;
result.openGraphData.Add(property, theVal);

Let me know if this is a good thing and if you think this could help for other cases (other websites doing that).

**Comment by ghorsey** [comment]
@coronag maybe I'm just missing what you are trying to explain on this ticket.  When I go to the url you've specified in this ticket and extract and execute the og:image content and execute it in a browser, I'm getting an access denied xml response, and the url format isn't something like a `data:image/png;base64,...` format.  I'm a little unclear on how to resolve this ticket.....

**Comment by coronag** [comment]
@ghorsey - on the given url, the og:image url is : 

https://tn.periscope.tv/lXc5gSh6UPaWdc37LtVCb3UdtSfvj2QNutojPK2du5YWrNchfI4wXpwwHKTyfDhmfT2ibsBZV4doQeWlhSvI4A==/chunk_314.jpg?Expires=1781852253&amp;Signature=U5OY3Y2HRb4ETmakQAPwMcv~bqu6KygIxriooa41rk64RcDfjww~qpVgMR-T1iX4S9NxfvXHLMT3pEckBDEOicsNO7oUAo4NieH9GRB2Sv0EA7swxLojD~Zn98ThNWTF5fSzv6SSPjyvctsqBiRmvAN6x7fmMH6l3vzx8ePSCgdEm8-31lUAz7lReBNZQjYSi~C8AwqZVI0Mx6y8lNKklL~m0e6RTGdvr~-KIDewU3wpjSdX7AgpaXXjahk4x-ceUUKcH3T1j--ZjaY7nqPO9fbMZFNPs502A32mrcmaZCzvaD~AuoH~u3y44mJVjzHRrpTxHIBklqHxAgc7dzverg__&amp;Key-Pair-Id=APKAIHCXHHQVRTVSFRWQ

=> it shows an error and an xml response
=> if you replace "&amp;" with "&" in that url you got the real image working url 
=> I just fixed that issue we have with that website doing "System.Web.HttpUtility.HtmlDecode((value ?? ""))" (only on the og:image tag value) ... as visible on that fork commit : 
https://github.com/sociabble/OpenGraph-Net/commit/365981f5b130b95d15f48f84ee609bb9349e17c5


So I have created that issue in case this might happen more than once and in case this can help :)

**Comment by ghorsey** [comment]
This is fixed in v1.3.3.  Thank you for the report @coronag !
