### ISSUE TITLE
Charset issue

### ISSUE THREAD

**Issue by coronag** [ghorsey/OpenGraph-Net#6]
Just had an issue with character encoding for og:title and og:description with that URL : http://www.telerama.fr/cinema/realite-virtuelle-360-de-bonheur-a-ameliorer,144339.php?utm_medium=Social&utm_source=Twitter&utm_campaign=Echobox&utm_term=Autofeed#link_time=1466595239

If it can help - I have fixed it on my fork here :
https://github.com/sociabble/OpenGraph-Net/commit/321ce50126b6a4c6c0da729a53fce49f2b90290f

**Comment by ghorsey** [comment]
This is fixed in v1.3.3.  Thank you for the report @coronag !
