### ISSUE TITLE
Extensible html parsing strategies

### ISSUE THREAD

**Issue by ghorsey** [ghorsey/OpenGraph-Net#8]
As described in this pull request https://github.com/ghorsey/OpenGraph-Net/pull/2 from @DamianMac. Replace the html parsing code with a strategy that can be replaced by consumers of the OpenGraph.net

**Comment by bartvanderwal** [comment]
+1

**Comment by ghorsey** [comment]
Now that I've updated the project to support .net core I'll look into adding this feature.

**Comment by ghorsey** [comment]
Hi @bartvanderwal  and @perosb, 
Instead of doing this, I ended up fully implementing the OpenGraph Protocol. 

Now instead of parsing strategies, anything under the known 13 namespaces will be automatically picked up and processed:

* og: http://ogp.me/ns#
  *  Expected fields when validating: `title`, `type`, `image`, `url`
* article: http://ogp.me/ns/article#
* book: http://ogp.me/ns/book#"
* books: http://ogp.me/ns/books#
* business http://ogp.me/ns/business#
* fitness: http://ogp.me/ns/fitness#
* game: http://ogp.me/ns/game#
* music: http://ogp.me/ns/music#
* place: http://ogp.me/ns/place#
* product: http://ogp.me/ns/product#
* profile: http://ogp.me/ns/profile#
* restaurant: http://ogp.me/ns/restaurant#
* video: http://ogp.me/ns/video#"

Any value specified after one of the above namespaces will now be picked up, even invalid ones such as: `<meta property="video:what" content="this is found">` .  You would access this in the graph as `graph.Metadata["video:what"].First()`

You also now have the ability to add a custom namespace to the parser via the `NamespaceRegistry`.  The code is pretty simple.  See the README.md file for more info :)

These changes are included in version 2.2, which I plan on publishing to nuget later today.
